"use client";

import { useState, ReactNode } from "react";

interface HelpTooltipProps {
  term: string;
  children: ReactNode;
  position?: "top" | "bottom" | "left" | "right";
}

// Financial term definitions
const financialGlossary: Record<string, { definition: string; example?: string; formula?: string }> = {
  // Valuation
  "DCF": {
    definition: "Discounted Cash Flow - A valuation method that estimates the present value of future cash flows.",
    example: "A company with $10M FCF growing 10% annually might have a DCF value of $150M at a 10% discount rate.",
    formula: "PV = Σ FCF/(1+r)^t + Terminal Value/(1+r)^n"
  },
  "Enterprise Value": {
    definition: "The total value of a business, including both equity and debt, minus cash.",
    formula: "EV = Market Cap + Total Debt - Cash"
  },
  "WACC": {
    definition: "Weighted Average Cost of Capital - The average rate of return required by all investors.",
    formula: "WACC = (E/V × Re) + (D/V × Rd × (1-T))"
  },
  "Terminal Value": {
    definition: "The estimated value of a business beyond the explicit forecast period, assuming perpetual growth.",
    formula: "TV = FCF × (1 + g) / (WACC - g)"
  },

  // Profitability
  "EBITDA": {
    definition: "Earnings Before Interest, Taxes, Depreciation, and Amortization - A measure of operating profitability.",
    formula: "EBITDA = Revenue - COGS - OpEx (excluding D&A)"
  },
  "Gross Margin": {
    definition: "The percentage of revenue remaining after deducting cost of goods sold.",
    formula: "Gross Margin = (Revenue - COGS) / Revenue"
  },
  "Operating Margin": {
    definition: "The percentage of revenue remaining after all operating expenses.",
    formula: "Operating Margin = EBIT / Revenue"
  },
  "Net Margin": {
    definition: "The percentage of revenue remaining as profit after all expenses.",
    formula: "Net Margin = Net Income / Revenue"
  },

  // Growth
  "CAGR": {
    definition: "Compound Annual Growth Rate - The geometric mean annual growth rate over multiple periods.",
    example: "Revenue growing from $1M to $2M over 5 years has a CAGR of 14.9%",
    formula: "CAGR = (End Value / Start Value)^(1/n) - 1"
  },
  "YoY": {
    definition: "Year-over-Year - The change compared to the same period in the previous year.",
    example: "Q1 2024 revenue of $5M vs Q1 2023 of $4M = 25% YoY growth"
  },

  // Cash Flow
  "Free Cash Flow": {
    definition: "Cash generated by operations after accounting for capital expenditures.",
    formula: "FCF = Operating Cash Flow - CapEx"
  },
  "Operating Cash Flow": {
    definition: "Cash generated from core business operations.",
    formula: "OCF = Net Income + D&A - Change in Working Capital"
  },
  "Working Capital": {
    definition: "Short-term assets minus short-term liabilities needed to run daily operations.",
    formula: "WC = Current Assets - Current Liabilities"
  },

  // SaaS Metrics
  "LTV": {
    definition: "Lifetime Value - The total revenue expected from a customer over their entire relationship.",
    formula: "LTV = ARPU × Customer Lifetime"
  },
  "CAC": {
    definition: "Customer Acquisition Cost - The total cost to acquire a new customer.",
    formula: "CAC = (Sales + Marketing Costs) / New Customers"
  },
  "LTV:CAC": {
    definition: "The ratio of customer lifetime value to acquisition cost. A ratio above 3:1 is generally healthy.",
    example: "An LTV of $3,000 with a CAC of $1,000 = 3:1 ratio"
  },
  "Churn Rate": {
    definition: "The percentage of customers who cancel their subscription in a given period.",
    formula: "Churn = Lost Customers / Starting Customers"
  },
  "MRR": {
    definition: "Monthly Recurring Revenue - Predictable revenue from subscriptions each month.",
    formula: "MRR = Number of Subscribers × ARPU"
  },
  "ARR": {
    definition: "Annual Recurring Revenue - The annualized value of subscription revenue.",
    formula: "ARR = MRR × 12"
  },
  "NRR": {
    definition: "Net Revenue Retention - Revenue from existing customers including expansion, minus churn.",
    formula: "NRR = (Starting MRR + Expansion - Contraction - Churn) / Starting MRR"
  },

  // Multiples
  "EV/Revenue": {
    definition: "Enterprise value as a multiple of revenue. Used to compare valuations across companies.",
    example: "A company with $10M revenue and $50M EV has a 5x EV/Revenue multiple"
  },
  "EV/EBITDA": {
    definition: "Enterprise value as a multiple of EBITDA. A common valuation metric.",
    example: "Industry average multiples range from 8-15x for growth companies"
  },
  "P/E Ratio": {
    definition: "Price-to-Earnings ratio - Stock price divided by earnings per share.",
    formula: "P/E = Stock Price / EPS"
  },

  // M&A
  "Accretion": {
    definition: "When an acquisition increases the acquirer's earnings per share.",
    example: "A deal is accretive if post-deal EPS is higher than pre-deal EPS"
  },
  "Dilution": {
    definition: "When an acquisition decreases the acquirer's earnings per share.",
    example: "Issuing new shares to fund a deal can dilute existing shareholders"
  },
  "Synergies": {
    definition: "Cost savings or revenue enhancements achieved by combining two companies.",
    example: "Eliminating duplicate departments might save $5M annually"
  }
};

export function HelpTooltip({ term, children, position = "top" }: HelpTooltipProps) {
  const [isVisible, setIsVisible] = useState(false);
  const info = financialGlossary[term];

  if (!info) {
    return <>{children}</>;
  }

  const positionClasses = {
    top: "bottom-full left-1/2 -translate-x-1/2 mb-2",
    bottom: "top-full left-1/2 -translate-x-1/2 mt-2",
    left: "right-full top-1/2 -translate-y-1/2 mr-2",
    right: "left-full top-1/2 -translate-y-1/2 ml-2",
  };

  const arrowClasses = {
    top: "top-full left-1/2 -translate-x-1/2 border-t-zinc-800",
    bottom: "bottom-full left-1/2 -translate-x-1/2 border-b-zinc-800",
    left: "left-full top-1/2 -translate-y-1/2 border-l-zinc-800",
    right: "right-full top-1/2 -translate-y-1/2 border-r-zinc-800",
  };

  return (
    <span
      className="relative inline-flex items-center gap-1 cursor-help"
      onMouseEnter={() => setIsVisible(true)}
      onMouseLeave={() => setIsVisible(false)}
    >
      {children}
      <svg className="w-3.5 h-3.5 text-zinc-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>

      {isVisible && (
        <div
          className={`absolute z-50 w-72 p-4 bg-zinc-800 border border-zinc-700 rounded-xl shadow-xl ${positionClasses[position]} animate-fade-in`}
        >
          <h4 className="font-semibold text-white mb-2">{term}</h4>
          <p className="text-sm text-zinc-300 mb-2">{info.definition}</p>

          {info.formula && (
            <div className="mt-2 p-2 bg-zinc-900 rounded-lg">
              <span className="text-xs text-zinc-500">Formula:</span>
              <code className="block text-xs text-amber-400 mt-1 font-mono">{info.formula}</code>
            </div>
          )}

          {info.example && (
            <div className="mt-2 p-2 bg-zinc-900/50 rounded-lg border border-zinc-700">
              <span className="text-xs text-zinc-500">Example:</span>
              <p className="text-xs text-zinc-400 mt-1">{info.example}</p>
            </div>
          )}
        </div>
      )}
    </span>
  );
}

// Simplified version for inline use
export function QuickHelp({ term }: { term: string }) {
  const [isVisible, setIsVisible] = useState(false);
  const info = financialGlossary[term];

  if (!info) return null;

  return (
    <span
      className="relative inline-flex ml-1 cursor-help"
      onMouseEnter={() => setIsVisible(true)}
      onMouseLeave={() => setIsVisible(false)}
    >
      <svg className="w-4 h-4 text-zinc-500 hover:text-zinc-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>

      {isVisible && (
        <div className="absolute z-50 w-64 p-3 bg-zinc-800 border border-zinc-700 rounded-lg shadow-xl bottom-full left-1/2 -translate-x-1/2 mb-2 animate-fade-in">
          <p className="text-xs text-zinc-300">{info.definition}</p>
          {info.formula && (
            <code className="block text-xs text-amber-400 mt-2 font-mono p-1.5 bg-zinc-900 rounded">{info.formula}</code>
          )}
        </div>
      )}
    </span>
  );
}

// Glossary panel for showing all terms
export function GlossaryPanel({ isOpen, onClose }: { isOpen: boolean; onClose: () => void }) {
  const [search, setSearch] = useState("");
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);

  if (!isOpen) return null;

  const categories = {
    Valuation: ["DCF", "Enterprise Value", "WACC", "Terminal Value"],
    Profitability: ["EBITDA", "Gross Margin", "Operating Margin", "Net Margin"],
    Growth: ["CAGR", "YoY"],
    "Cash Flow": ["Free Cash Flow", "Operating Cash Flow", "Working Capital"],
    "SaaS Metrics": ["LTV", "CAC", "LTV:CAC", "Churn Rate", "MRR", "ARR", "NRR"],
    Multiples: ["EV/Revenue", "EV/EBITDA", "P/E Ratio"],
    "M&A": ["Accretion", "Dilution", "Synergies"],
  };

  const filteredTerms = Object.entries(financialGlossary).filter(([term]) =>
    term.toLowerCase().includes(search.toLowerCase()) &&
    (!selectedCategory || Object.entries(categories).find(([cat, terms]) =>
      cat === selectedCategory && terms.includes(term)
    ))
  );

  return (
    <>
      <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50" onClick={onClose} />
      <div className="fixed inset-y-0 right-0 w-full max-w-lg bg-zinc-900 border-l border-zinc-800 z-50 overflow-hidden flex flex-col">
        {/* Header */}
        <div className="p-4 border-b border-zinc-800">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold text-white">Financial Glossary</h2>
            <button
              onClick={onClose}
              className="p-2 rounded-lg text-zinc-400 hover:text-white hover:bg-zinc-800"
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          {/* Search */}
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search terms..."
            className="w-full px-4 py-2 bg-zinc-800 border border-zinc-700 rounded-lg text-white placeholder-zinc-500"
          />

          {/* Categories */}
          <div className="flex flex-wrap gap-2 mt-3">
            <button
              onClick={() => setSelectedCategory(null)}
              className={`px-3 py-1 rounded-full text-xs font-medium transition-colors ${
                !selectedCategory ? "bg-amber-500 text-black" : "bg-zinc-800 text-zinc-400 hover:text-white"
              }`}
            >
              All
            </button>
            {Object.keys(categories).map((cat) => (
              <button
                key={cat}
                onClick={() => setSelectedCategory(cat === selectedCategory ? null : cat)}
                className={`px-3 py-1 rounded-full text-xs font-medium transition-colors ${
                  selectedCategory === cat ? "bg-amber-500 text-black" : "bg-zinc-800 text-zinc-400 hover:text-white"
                }`}
              >
                {cat}
              </button>
            ))}
          </div>
        </div>

        {/* Terms List */}
        <div className="flex-1 overflow-auto p-4 space-y-3">
          {filteredTerms.map(([term, info]) => (
            <div key={term} className="p-4 bg-zinc-800/50 border border-zinc-700 rounded-xl">
              <h3 className="font-semibold text-white mb-2">{term}</h3>
              <p className="text-sm text-zinc-300 mb-2">{info.definition}</p>
              {info.formula && (
                <code className="block text-xs text-amber-400 font-mono p-2 bg-zinc-900 rounded mt-2">
                  {info.formula}
                </code>
              )}
              {info.example && (
                <p className="text-xs text-zinc-500 mt-2 italic">{info.example}</p>
              )}
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
